service: youtube-media-install

frameworkVersion: "3"
configValidationMode: error

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:GetQueueUrl
        - sqs:ReceiveMessage
        - sqs:GetQueueAttributes
      Resource:
        - arn:aws:sqs:${self:provider.region}:${aws:accountId}:medias-to-install

functions:
  install:
    handler: src/handlers/install.handler
    dependsOn:
      - MediasToInstallQueue
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${aws:accountId}:medias-to-install

resources:
  Resources:
    MediasToInstallQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: medias-to-install
        MessageRetentionPeriod: 43200 # 12 hours
