name: Build, Test and Deploy

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  worker:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Serverless config
        if: contains(github.ref, 'main')
        run: |
          npx serverless config credentials \
            --provider aws \
            --key ${{ secrets.AWS_ACCESS_KEY_ID }} \
            --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} \

      - name: Deploy to production
        if: contains(github.ref, 'main')
        run: npm run deploy
